### PR TITLE
Apply patch to ruby-xslt library

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- https://github.com/metanorma/metanorma/issues/41

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 

1. Please do not use `gsub` for file paths.
2. AppVeyor build is still failing. 

Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse ok, BTW PR is not ready to review yet

**Comment by ronaldtse** [comment]
Perhaps `File.dirname(__FILE__)` is not giving you the correct separator?

Or you could use `Pathname(__FILE__)`?

**Comment by CAMOBAP795** [comment]
> Perhaps File.dirname(__FILE__) is not giving you the correct separator? 

Instead 'correct' let use 'platform-dependent' or 'platform-independent'

`File.dirname(__FILE__)` give path with `/` separator on any platform 

> Or you could use Pathname(__FILE__)?

Looks like no

----

Looks like my general idea was wrong because error has been thrown from this place `https://github.com/glejeune/ruby-xslt/blob/master/ext/xslt_lib/parser.c#L140`

According to this `fopen` succeed, and this means that provided path are ok, highly likely the error related to this https://stackoverflow.com/questions/3187693/fread-ftell-apparently-broken-under-windows-works-fine-under-linux

Unfortunately I haven't windows laptop right now, and haven't change to install VM yet, I will try my best to check this assumption on next week

**Comment by ronaldtse** [comment]
Yes, just have to do in the correct way. Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse @opoudjis looks like my assumption was right because after [applying patch](https://stackoverflow.com/questions/3187693/fread-ftell-apparently-broken-under-windows-works-fine-under-linux) `ruby-xslt` issue gone

But now we have a problem: https://github.com/glejeune/ruby-xslt - looks very outdated I can submit PR to it but I not sure that author will respond. I see several way to solve it
1. Don't install `ruby-xslt` from `rubygems.org` and use git + apply patch before compiling
2. Made own fork on github and apply fix to it update all gemspec to point to our repo (AFAIK it's technically possible)
3. Make PR and wait)

@ronaldtse @opoudjis how do you think?

**Comment by ronaldtse** [comment]
Nokogiri has XSLT support. Can we switch from ruby-xslt?

**Comment by CAMOBAP795** [comment]
@ronaldtse maybe as I see in `gemfile` we have both
```
  spec.add_dependency "nokogiri"
  spec.add_dependency "ruby-xslt"
```

Yep and `nokogiri` have XSLT API https://www.rubydoc.info/github/sparklemotion/nokogiri/Nokogiri/XSLT/Stylesheet

@opoudjis is there any reason why we use XSLT API from `ruby-xslt` rather then from `nokogiri`?

**Comment by CAMOBAP795** [comment]
@ronaldtse @opoudjis BTW https://github.com/glejeune/ruby-xslt/pull/10 was merged

**Comment by ronaldtse** [comment]
Great. However, the question still stands. If we can handle with Nokogiri, we probably don’t need ruby-xslt ?

**Comment by CAMOBAP795** [comment]
@ronaldtse I agree with you, let me prepare another PR for this

**Comment by CAMOBAP795** [comment]
closed in favor of https://github.com/metanorma/omml2mathml/pull/5

**Comment by opoudjis** [comment]
Didn't get to this, but yes, that was old code, and I have in fact had to switch ruby-xslt out for Nokogiri XSLT in another gem already.

**Pull request closed without merging**
