### PR TITLE
Remove ruby-xslt dependency

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- related PR https://github.com/metanorma/omml2mathml/pull/4

### CODE REVIEW

**Comment by CAMOBAP795** [comment]
I'm not sure that my solution optimal because we do unnecessary marshaling `Nokogiri::XML::Element->String->Nokogiri::XML::Document` 

@opoudjis maybe there is cheep/optimal way to convert `Nokogiri::XML::Element->Nokogiri::XML::Document` 

I sure that `x.to_xml.sub(/<m:(oMath|oMathPara)>/,"<m:\\1 xmlns:m='http://schemas.openxmlformats.org/officeDocument/2006/math'>")` need to be replaced with [`add_namespace_definition`](https://www.rubydoc.info/github/sparklemotion/nokogiri/Nokogiri/XML/Node#add_namespace_definition-instance_method) because it's not cover the case when prefix is different then `m` correct me if I'm wrong

**Comment by ronaldtse** [comment]
The thing about Nokogiri is that the methods are confusing and hard to find out how to do the right thing...

**Comment by CAMOBAP795** [comment]
@opoudjis may I kindly ask you to explain logic behind this AFAIK using `gsub` instead of xml API very dangerous here

**Comment by opoudjis** [comment]
@CAMOBAP795 Given that Microsoft Word's processing of Word HTML is quite primitive, and that the namespace prefix values are explicitly set for Word at the beginning of HTML template, it would be far more dangerous to allow the prefix of MathML to be anything but `m:`. We are not dealing with a well-functioning XML parser here: we are dealing with a fairly crude, template-driven XML parser in Microsoft Word. There will not be a case when the MathML prefix is anything but `m:`.

I'm accepting the changes. I will look into seeing if I can pass a Nokogiri element into XSLT, and sticking the element into a dummy document might be faster.

**Comment by CAMOBAP795** [comment]
> I'm accepting the changes. I will look into seeing if I can pass a Nokogiri element into XSLT, and sticking the element into a dummy document might be faster.

BTW I have found a way to do this 
```
doc = Nokogiri::XML::Document::new()
doc.root = x.dup()
```

But this will make no sense because of `gsub`

@opoudjis sorry for obsession, but just to be on the same page:
 - Final document from `omml2mathml_spec.rb` test invalid because "281 | The prefix "mml" for element "mml:math" is not bound."
 - Because this I propose to not delete namespaces with `gsub` and just traverse DOM
 - Maybe also make sense to use XSD for result validation https://www.w3.org/Math/XMLSchema/ ?

**Comment by opoudjis** [comment]
This is old standalone code that we have not ended up using, because instead we used the OMML to MathML converter embedded in work-to-markdown. I was originally insisting on namespaces because of how the code would be embedded into our process, but given that this is now standalone code, that is no longer a requirement.

For that reason, I accept that I can make these changes. For the same reason, those changes are at a very low priority for me to make, since this does not impact any of our code; given my workload for Ribose, I don't think I will ever get to them unless someone tells me to. If you'd like to, feel free; the changes are straightforward enough.

**Comment by opoudjis** [comment]
https://github.com/metanorma/omml2mathml/issues/6

**Pull request merged**
